package KaPo;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class StarwarsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void starwars() {
    driver.get("https://en.wikipedia.org/wiki/Star_Wars");
    driver.manage().window().setSize(new Dimension(785, 824));
    driver.findElement(By.linkText("George Lucas")).click();
    js.executeScript("window.scrollTo(0,529.5999755859375)");
    driver.findElement(By.linkText("Lucasfilm Games")).click();
    driver.findElement(By.linkText("The Walt Disney Company")).click();
  }
}
